/* eslint-disable @typescript-eslint/no-explicit-any */

/** Virtual module generated by withWebMCP — resolved via bundler alias */
declare module "@webmcp/actions" {
  export const actions: Record<string, (...args: any[]) => any>;
}
