import { readdirSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import type { NextConfig } from "next";
import type { WebMCPConfig } from "./types.js";

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Synchronously scans the app directory for server actions and component
 * resource data functions that need to be auto-imported.
 */
const findAutoImports = (
  appDir: string
): Array<{ filePath: string; exportNames: string[] }> => {
  const results: Array<{ filePath: string; exportNames: string[] }> = [];

  const scan = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        scan(fullPath);
      } else if (
        /\.(ts|tsx|js|jsx)$/.test(entry.name) &&
        !/route\.(ts|tsx|js|jsx)$/.test(entry.name)
      ) {
        const source = readFileSync(fullPath, "utf-8");
        const exportNames: string[] = [];

        // "use server" files: scan for actions
        if (/^["']use server["']/m.test(source)) {
          // Pattern 1: fn.tool = { ... }
          const toolPattern = /(\w+)\.tool\s*=/g;
          let match;
          while ((match = toolPattern.exec(source)) !== null) {
            if (!exportNames.includes(match[1])) exportNames.push(match[1]);
          }

          // Pattern 2: export const X = actionClient.use(mcp(...)).inputSchema(...).action(...)
          const chainPattern =
            /export\s+const\s+(\w+)\s*=\s*\w+\s*[\n\r]*\s*\./g;
          while ((match = chainPattern.exec(source)) !== null) {
            if (!exportNames.includes(match[1])) exportNames.push(match[1]);
          }
        }

        // Component resource files: scan for .resource = { data: funcName }
        const resourcePattern = /\w+\.resource\s*=\s*\{[^}]*data\s*:\s*(\w+)/g;
        let resourceMatch;
        while ((resourceMatch = resourcePattern.exec(source)) !== null) {
          const dataFn = resourceMatch[1];
          if (!exportNames.includes(dataFn)) exportNames.push(dataFn);
        }

        if (exportNames.length > 0) {
          results.push({ filePath: fullPath, exportNames });
        }
      }
    }
  };

  scan(appDir);
  return results;
};

/**
 * Generates a module that statically imports all discovered server actions
 * and exports them as a record. The bundler can resolve these static imports.
 */
const generateActionsModule = (appDir: string, outputDir: string): string => {
  const actions = findAutoImports(appDir);
  const outputPath = join(outputDir, "actions.js");

  mkdirSync(outputDir, { recursive: true });

  const lines: string[] = [
    "// Auto-generated by next-webmcp — do not edit",
  ];
  const allExports: string[] = [];

  for (const { filePath, exportNames } of actions) {
    // Compute relative path from output dir to the action file
    let relPath = relative(outputDir, filePath);
    // Ensure forward slashes for import paths
    if (sep === "\\") relPath = relPath.replace(/\\/g, "/");
    // Strip .ts/.tsx extension (bundler resolves it)
    relPath = relPath.replace(/\.tsx?$/, "");
    // Ensure it starts with ./
    if (!relPath.startsWith(".")) relPath = `./${relPath}`;

    lines.push(`import { ${exportNames.join(", ")} } from "${relPath}";`);
    allExports.push(...exportNames);
  }

  lines.push("");
  lines.push(`export const actions = { ${allExports.join(", ")} };`);
  lines.push("");

  writeFileSync(outputPath, lines.join("\n"));
  return outputPath;
};

/**
 * Next.js plugin wrapper that configures WebMCP integration.
 *
 * - Scans for server actions and generates a static import module
 * - Adds resolve aliases so the handler can import discovered actions
 * - Rewrites `/.well-known/mcp` to the manifest endpoint
 *
 * Usage in next.config.ts:
 * ```ts
 * import { withWebMCP } from 'next-webmcp';
 * export default withWebMCP()(nextConfig);
 * ```
 */
export const withWebMCP =
  (mcpConfig: WebMCPConfig = {}) =>
  (nextConfig: NextConfig): NextConfig => {
    const projectRoot = process.cwd();
    const appDir = join(projectRoot, "app");
    const outputDir = join(projectRoot, ".next-webmcp");
    generateActionsModule(appDir, outputDir);
    // Relative path from project root for Turbopack
    const actionsRelative = "./.next-webmcp/actions.js";

    return {
      ...nextConfig,
      env: {
        ...nextConfig.env,
        WEBMCP_CONFIG: JSON.stringify(mcpConfig),
      },
      // Add resolve alias for the generated actions module
      turbopack: {
        ...(nextConfig as any).turbopack,
        resolveAlias: {
          ...(nextConfig as any).turbopack?.resolveAlias,
          "@webmcp/actions": actionsRelative,
        },
      },
      webpack: (config, options) => {
        config.resolve = config.resolve ?? {};
        config.resolve.alias = config.resolve.alias ?? {};
        (config.resolve.alias as Record<string, string>)["@webmcp/actions"] =
          join(outputDir, "actions.js");
        return nextConfig.webpack?.(config, options) ?? config;
      },
      // Rewrite /.well-known/mcp to our internal handler
      async rewrites() {
        const existingRewrites = await nextConfig.rewrites?.();
        const mcpRewrites = [
          {
            source: "/.well-known/mcp",
            destination: "/api/mcp/manifest",
          },
        ];

        if (Array.isArray(existingRewrites)) {
          return [...existingRewrites, ...mcpRewrites];
        }

        if (existingRewrites) {
          return {
            ...existingRewrites,
            afterFiles: [
              ...(existingRewrites.afterFiles ?? []),
              ...mcpRewrites,
            ],
          };
        }

        return mcpRewrites;
      },
    };
  };
